### ISSUE TITLE
/tmp typically too small for this

### ISSUE THREAD

**Issue by nkadel** [mmornati/docker-mock-rpmbuilder#17]
For bulkier RPM's and build areas, /tmp is typically way too small for bulkier builds, such as gcc, and in high security environments it's mounted with "noexec" and "nosuid". Even if the software compiles, this can break test building.

Instead, use "/var/cache/docker-mock/" or some similarly specific directory.

**Comment by mmornati** [comment]
I recheck the scripts, the `/tmp` folder is only used as temporary to change a `.cfg` file but not for the build.
It is only inside the documentation where I put an example using the temp folder. I will change the README following your suggestion.

If you have any other place where the temp folder is used, can you please point me to that file?
