### ISSUE TITLE
docker.io/mmornati/mockrpmbuilder ... not found

### ISSUE THREAD

**Issue by d33tah** [mmornati/docker-mock-rpmbuilder#3]
`$ sudo docker run -d -e MOCK_CONFIG=epel-6-i386 -e SOURCE_RPM=git-2.3.0-1.el7.centos.src.rpm -v /tmp/rpmbuild:/rpmbuild --privileged=true mmornati/mockrpmbuilder
zsh: correct '/tmp/rpmbuild:/rpmbuild' to '/tmp/rpmbuild/rpmbuild' [nyae]? n
Unable to find image 'mmornati/mockrpmbuilder:latest' locally
Trying to pull repository docker.io/mmornati/mockrpmbuilder ... not found
FATA[0007] Error: image mmornati/mockrpmbuilder:latest not found`

Let me know if you need more details.

**Comment by asashnov** [comment]
https://blog.mornati.net/docker-rpm-builder-container/

First off all you need to build the docker container:

```
git clone https://github.com/mmornati/docker-mock-rpmbuilder.git
cd docker-mock-rpmbuilder
docker build -t mmornati/mockrpmbuilder .
```

**Comment by jgillich** [comment]
Why isn't this on Docker Hub? @mmornati

**Comment by mmornati** [comment]
Good question. I never thought to put it on Docker hub.
But I'll do it :)

**Comment by mmornati** [comment]
@jgillich pushed on docker hub. 
I'll need more time for work on cool things :+1:
